tabela = ("Flamengo ", "Palmeiras", "Athletico-PR", "Fluminense", "Bahia", "Cruzeiro", "Atlético-MG", "Santos", "Coritiba", "Red Bull Bragantino", "São Paulo", "Botafogo", "Vitória", "Corinthians", "Mirassol", "Vasco", "Grêmio", "Internacional", "Remo", "Chapecoense")
print("=-="*20)
print(f"lista de times do Brasileirão: {tabela}")
print("=-="*20)
print(f"Os 5 primeiros são: {tabela[0:5]}")
print("=-="*20)
print(f"Os 4 ultimos são: {tabela[-4:]} ")
print("=-="*20)
print(f"Times em ordem alfabética: {sorted(tabela)} ")
print("=-="*20)
print(f"O Chapeconense esta na {(tabela.index("Chapecoense")) + 1}ª posição.")
