n=str(input("digite seu nome completo:")).strip()
print("Analisando seu nome...")
print(f"Seu nome em maisculo é {n.upper()}")
print(f"Seu nome em letras minusculas é {n.lower()}")
print("Seu nome tem ao todo {} LETRAS".format(len(n.replace(" ",""))))
print(f"Seu primeiro nome é {n.split()[0]} e tem {len(n.split()[0])} LETRAS")
