n=str(input("digite seu nome completo:")).strip()
print("Analisando seu nome...")
print("Seu nome em maisculo é {}".format(n.upper()))
print("Seu nome em letras minusculas é {}".format(n.lower()))
print("Seu nome tem ao todo {} LETRAS".format(len(n.replace(" ",""))))
print("Seu primeiro nome é {} e tem {} LETRAS".format(n.split()[0], len(n.split()[0])))
