m1=input("digite algo:")
print("você digitou {}".format(m1))
print("o tipo primitivo desse valor é",type(m1))
print("o valor é numérico?",m1.isdigit())
print("o valor é alphabetic?",m1.isalpha())
print("o valor é alfanumérico?",m1.isalnum())
print("o valor é maiúsculo?",m1.isupper())
print("o valor é minúsculo?",m1.islower())
print("o valor é capitalizado?",m1.istitle())
print("o valor é decimal?",m1.isdecimal())
print("o valor é espaço?",m1.isspace())
print("o valor é imprimível?",m1.isprintable())
print("o valor é identificador?",m1.isidentifier())
print("o valor é um número?",m1.isnumeric())
print("o valor é um dígito?",m1.isdigit())
print("o valor é um caractere ASCII?",m1.isascii())
if m1.isnumeric():print(int(m1)+1)
